<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="GopinathKumsi" ignored="0" name="Test" tests="1" failures="1" timestamp="2020-06-17T15:49:25 IST" time="4.24" errors="0">
  <testcase name="getDetailsOfWeather" time="4.137" classname="com.test.SecondTest">
    <failure type="java.lang.AssertionError" message="expected [201] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [500]
at com.test.SecondTest.getDetailsOfWeather(SecondTest.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- getDetailsOfWeather -->
</testsuite> <!-- Test -->
